:imagesdir: images
:couchbase_version: current
:toc:
:project_id: gs-how-to-kubernetes
:icons: font
:source-highlighter: prettify
:tags: guides,meta

= Getting started with kubernetes

== RUN/CREATE/APPLY
[source,bash]
----
kubectl run [podname] --image=nginx:alpine 
----

[source,bash]
----
kubectl create -f file.yml --dry-run --validate=true
----

[source,bash]
----
kubectl create -f file.yml --save-config
----

[source,bash]
----
kubectl create -f file.yml 
----

Deploy everything(deployment, services etc) in a folder 
[source,bash]
----
kubectl create -f <folder_path>  --save-config
----

[source,bash]
----
kubectl apply -f file.yml
----

Dynamically pipe file output
[source,bash]
----
export TARGET_ROLE=blue
export IMAGE_VERSION=nginx-blue
cat nginx.deployment.yml | sh config.sh | kubectl create --save-config -f -
----

Create a secret and store securely in kubernetes
[source,bash]
----
kubectl create secret generic [name] \
    --from-literal=[key]=[value]
----
Create a secret from a file
[source,bash]
----
kubectl create secret generic my-secret \
    --from-file=ssh-privatekey=~/.ssh/id_rsa \
    --from-file=ssh-publickey=~/.ssh/id_rsa.pub
---- 
Create a secret from a key pair
[source,bash]
----
kubectl create secret tls tls-secret --cert=path/to/tls.cert
    --key=path/to/tls.key
---- 


== GET INFO
[source,bash]
----
kubectl get all
----

[source,bash]
----
kubectl get pods
----

[source,bash]
----
kubectl get deployments
----

List all deployments and their labels
[source,bash]
----
kubectl get deployments --show-labels
----

Get all deployments with a specific label
[source,bash]
----
kubectl get deployments -l app=nginx
----

[source,bash]
----
kubectl get services
----

[source,bash]
----
kubectl get pods -o wide
----

[source,bash]
----
kubectl get pod [name-of-pod] -o yaml
----

[source,bash]
----
kubectl get cm [cm-name] -o yaml
----

[source,bash]
----
kubectl get secrets
----

[source,bash]
----
kubectl get secrets [secret-name] -o yaml
----

== DESCRIBE
[source,bash]
----
kubectl describe [pod | deployment] [pod-name | deployment-name]
----

== EDIT
[source,bash]
----
kubectl edit -f [path-to-yml-file]
----

== Delete
[source,bash]
----
kubectl delete pod [name-of-pod]
----

[source,bash]
----
kubectl delete deployment [name-of-deployment]
----

[source,bash]
----
kubectl delete service [name-of-service]
----

[source,bash]
----
kubectl delete -f [path-to-YAML-file]
----
Delete all kinds of service of the files in a given folder
[source,bash]
----
kubectl delete -f [path-to-folder]
----

== PORT FORWARD

Listen on port 8080 locally and forward to port 80 in pod - `external port:Internal port`
[source,bash]
----
kubectl port-forward pod/[pod-name] 8080:80
----

Listen on port 8080 locally and forward to Deployment's Pod
[source,bash]
----
kubectl port-forward deployment/[deployment-name] 8080:80
----

Listen on port 8080 locally and forward to Service's Pod
[source,bash]
----
kubectl port-forward service/[service-name] 8080
----

== SCALE

[source,bash]
----
kubectl scale deployment [deployment-name] --replicas=5
----

[source,bash]
----
kubectl scale -f file.deployment.yml --replicas=5
----

== EXEC
[source,bash]
----
kubectl exec [pod-name] -it sh
----

[source,bash]
----
kubectl exec [pod-name] -- curl -s http://podIP
----

== CONFIGMAP
Create a ConfigMap using data from a config file
[source,bash]
----
kubectl create configmap [cm-name] --from-file=[path-to-file]
----
Create a ConfigMap from an env file
[source,bash]
----
kubectl create configmap [cm-name] --from-env-file=[path-to-file]
----
Create a ConfigMap from individual data values
[source,bash]
----
kubectl create configmap [cm-name]
    --from-literal=apiUrl=https://my-api
    --from-literal=otherKey=otherValue
----
Create from a ConfigMap manifest
----
kubectl create -f file.configmap.yml
----

== Deployment
Record the deployment. `-f ./` implies deploy all possible files on the given path
[source,bash]
----
kubectl create -f ./ --save-config --record
----
[source,bash]
----
kubectl apply -f file.deployment.yml --save-config --record
----
status
[source,bash]
----
kubectl rollout status deployment [deployment-name]
----
----
kubectl rollout status -f file.deployment.yml
----
Get information about a deployment
[source,bash]
----
kubectl rollout history deployment [deployment-name]
----
[source,bash]
----
kubectl rollout history deployment [deployment-name] --revision=2
----
Roll-back a deployment
[source,bash]
----
kubectl rollout undo -f file.deployment.yml
----
Roll-back to a specific version
[source,bash]
----
kubectl rollout undo deployment [deployment-name] --to-revision=2
----
